apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webserver
  labels:
    app: webserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      volumes:
        - name: html
          configMap:
            name: index-html-configmap
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
          - containerPort: 80
        volumeMounts:
          - mountPath: /usr/share/nginx/html/
            name: html
